!!ExportedWorkflow
apiVersion: torq.io/v2alpha
kind: Workflow
id: 71575d40-779b-405d-9ba7-49023f521985
name: Test Publish
trigger:
  onDemandTrigger:
    parameterList:
      parameters: []
playbook:
  steps:
    - name: us-docker.pkg.dev/stackpulse/public/virustotal/get-api-usage:2.2.0
      id: get_api_usage
      envFrom:
        integrationRef: ""
      uuid: a5903028-0f58-4ba6-9e91-1a767c44e14c
      pretty_name: Get API Usage
      options:
        executor:
          name: http_request_v_4_30_0
          env:
            AUTHORIZATION: None
            BODY: ""
            HEADERS: |-
              {
                "x-apikey": "{{ .VT_API_KEY | jsonEscape }}"
              }
            METHOD: GET
            PARSE_HJSON: "true"
            REQUIRED_VARIABLES: '["VT_API_KEY"]'
            TIMEOUT: "30"
            URL: '{{ .BASE_URL | default "https://www.virustotal.com/api/v3" }}/users/{{ .VT_API_KEY | urlEnc }}/api_usage'
          sync: true
          disable: false
      documentationUrl: https://developers.virustotal.com/reference/user-api-usage
      manifestId: 2494ec0c-f816-52e1-8115-757e35c0a021
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - name: us-docker.pkg.dev/stackpulse/public/torq/create-a-workspace-variable:2.1.0
      id: create_a_workspace_variable
      env:
        DATA_TYPE: string
        VALUE_STRING: ""
        VARIABLE_PRETTY_NAME: ""
      envFrom:
        integrationRef: ""
      uuid: 0eadee8d-67a7-466c-9a7a-e5014b7ce91f
      pretty_name: Create a workspace variable
      options:
        executor:
          name: http_request_v_4_21_0
          env: {}
          sync: true
          disable: false
      documentationUrl: https://learn.torq.io/v1/docs/workspace-variables
      manifestId: a1f13908-749d-5744-b974-b1238ea1e21b
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
    - if:
        conditions:
          or:
            - and:
                - lvalue: ""
                  operator: EQUALS
                  rvalue: ""
        then: []
        else: []
        uuid: d4448441-8039-4664-a69e-8fc6f973a5e5
        pretty_name: If
    - exit:
        success: "true"
        pretty_name: Exit
        output: '{}'
        uuid: df4a01d7-b63f-4a52-ae58-cff3724bb591
  output_schema: '{}'
root: true
